### PR TITLE
A bunch of refactoring and 2 bug fixes

### PR DESCRIPTION
**Pull request by DBloomTableau**
A bunch of piece by piece refactoring to make things easier to reason about, and then 2 simple bug fixes.

First is a race condition where thread A can `apr_file_write` just as thread B calls `apr_file_close` on that file. This is because while the lock surround the `close` call, doesn't actually surround the `write` call.

Basic fix is to switch to a RWLock to minimize contention.

Second fix is that the parent process usually never logs, and so never rotates file handles, which basically means it functionally leaks the handle. On certain OSes this can prevent the file from being deleted, which somewhat defeats the point of log rotation.

Basic fix is just to close the file on the parent process and reopen it on first write if needed.

There's also one other significant change, which is to delay setting the callbacks until `ap_hook_open_logs`. This simplifies the takeover of responsibilities.

### CODE REVIEW

**Comment by JBlond** [comment]
@DBloomTableau your patch looks promising. On which platforms did you test it?

**Comment by JBlond** [comment]
@SteffenAL can you test this on windows please?

**Comment by JBlond** [comment]
The Windows Version works fine. Thanks @SteffenAL for the testing!
I'll do some more testing on Debian before I merge it.

**Comment by SteffenAL** [comment]
There must be a new version number it is now 1.0.2.  Maybe up it to 1.1

**Comment by JBlond** [comment]
@DBloomTableau  One other feedback that I got is: 

> Noticed a diff with the old one.
> 
> **New:**
> When I enable the module without directives it is appending the current Unix timestamp  to  access.log.1568246400 (is current date).

> So it looks like that directive Rotatelogs is On by default

> When I expliciet set it to Off then no timestamp appended.

> **Old:**
> Enable module without directives no timestamp is added.

> I do not know what is does when you have more vhosts (tested without vhosts).

> Do not know what is preferred by Default

**Comment by JBlond** [comment]
@DBloomTableau pleace answer the question I have.

**Comment by JBlond** [comment]
> So it looks like that directive Rotatelogs is On by default

I can confirm this on Linux and windows.  _RotateLogs Off_ no longer works. So loading the module enables it and can not turned off my config. 

Since @DBloomTableau did not respond at I close this PR.

**Comment by JBlond** [comment]
@DBloomTableau please create two new PR's. One with the bug fix and later one with the refactoring. So we can see what caused the issue with RotateLogs Off

**Pull request closed without merging**
